### ISSUE TITLE
Upload to AUR

### ISSUE THREAD

**Issue by UnkwUsr** [tbocek/obs-source-all#4]
I think it worth uploading to AUR for easier discoverability, since long waited PR that could fix issue was closed: https://github.com/obsproject/obs-studio/pull/7475 .
My only concern is whether such a package would violate AUR rules. Idk, but probably not, if clearly state that in description: this package takes sources from not official release page (I mean from here, this repo).

P.S. thanks for your work

**Comment by tbocek** [comment]
Thanks, I was hoping that this issue is resolved quickly, but as of today, websocktes in OBS Arch are still not working due to not syncing the websocket submodule. I'm not sure if I should upload to AUR, as the only change is how I'm fetching the sources. BTW, I just updated to the latest version 30.1.2-2

**Comment by UnkwUsr** [comment]
> BTW, I just updated to the latest version 30.1.2-2

Thanks! I had problems building previous version, and started looking at `obs-studio-git` aur package (which also have problems on build...). But now your updated version is working. Thanks!

As for releasing to aur: I think this can save some time for people. For example look at [obs-studio-git](https://aur.archlinux.org/packages/): there is still recent comments full of pain because of building errors.

**Comment by tbocek** [comment]
Finally uploaded to aur: https://aur.archlinux.org/packages/obs-studio-with-websockets
